/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ActiveFilterDTO = { 
    /**
     * Актывный ли фильтр по умолчанию
     */
    active?: boolean;
    /**
     * Код записи
     */
    code?: string;
    /**
     * Помечен ли фильтр как не используемый
     */
    deleted?: boolean;
    /**
     * Идентификатор группы фильтров
     */
    groupId?: ActiveFilterDTO.GroupIdEnum;
    /**
     * Идентификатор записи
     */
    id?: number;
    /**
     * Наименования
     */
    name?: string;
};
export namespace ActiveFilterDTO {
    export type GroupIdEnum = 'SOURCE' | 'REGIONS' | 'LAYERS' | 'DEFECTS' | 'EVENTS' | 'SOURCE_GROUPS' | 'DISTRICTS';
    export const GroupIdEnum = {
      SOURCE: 'SOURCE' as GroupIdEnum,
      REGIONS: 'REGIONS' as GroupIdEnum,
      LAYERS: 'LAYERS' as GroupIdEnum,
      DEFECTS: 'DEFECTS' as GroupIdEnum,
      EVENTS: 'EVENTS' as GroupIdEnum,
      SOURCEGROUPS: 'SOURCE_GROUPS' as GroupIdEnum,
      DISTRICTS: 'DISTRICTS' as GroupIdEnum
    };
}