/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Объект дашлета
 */
export type DashletInfoDTO = { 
    /**
     * Дочерние объекты
     */
    children?: DashletInfoDTO[];
    /**
     * Цвет
     */
    color?: string;
    /**
     * Процент
     */
    percent?: number;
    /**
     * Описание
     */
    title?: string;
    /**
     * Тип
     */
    type?: string;
    /**
     * Значение
     */
    value?: number;
};