/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * объект для запроса поворота камер.
 */
export type EchdMoveCamera = { 
    /**
     * Список идентификаторов камер
     */
    cameraIds?: string[];
    /**
     * Широта
     */
    lat?: number;
    /**
     * Долгота
     */
    lng?: number;
};