/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Данные с ссылкой на плеер ЕЦХД
 */
export type EchdDataDTO = { 
    /**
     * Ссылка на внутрений плеер с архивным потоком ЕЦХД
     */
    urlEmbedPlayer?: string;
    /**
     * Ссылка на внутрений плеер с архивным потоком ЕЦХД
     */
    urlEmbedPlayerArchive?: string;
    /**
     * Ссылка на внутрений плеер с потоком ЕЦХД
     */
    urlEmbedPlayerLive?: string;
};