/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EchdPosition = { 
    /**
     * в качестве accessLevel в строке передается значение EveryOne
     */
    accessLevel?: string;
    /**
     * Идентификатор позиции
     */
    positionId?: string;
    /**
     * Идентификатор объекта наблюдения
     */
    surveillanceObjectId?: string;
    /**
     * Название позиции
     */
    title?: string;
};