/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Экземпляр маппинга поля к алиасу.
 */
export type FieldMappingDTO = { 
    /**
     * Алиас слоя
     */
    alias?: string;
    /**
     * Идентификатор атрибута
     */
    attributeId?: string;
    /**
     * Значение атрибута
     */
    attributeValue?: string;
    id?: number;
};