/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Фильтр поиска
 */
export type FilterSearch = { 
    field?: FilterSearch.FieldEnum;
    value?: string;
};
export namespace FilterSearch {
    export type FieldEnum = 'ADDRESS' | 'OBJECT_ID' | 'TICKET' | 'TRASH_CONTAINERS';
    export const FieldEnum = {
      ADDRESS: 'ADDRESS' as FieldEnum,
      OBJECTID: 'OBJECT_ID' as FieldEnum,
      TICKET: 'TICKET' as FieldEnum,
      TRASHCONTAINERS: 'TRASH_CONTAINERS' as FieldEnum
    };
}