/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Настройки
 */
export type KeyPropertyDTO = { 
    /**
     * Описание настройки
     */
    description?: string;
    /**
     * Состояние настроки - ВКЛ/ВЫКЛ
     */
    enabled?: boolean;
    /**
     * Идентификатор настройки
     */
    id?: number;
    /**
     * Ключ
     */
    key?: string;
    /**
     * Тип
     */
    type?: KeyPropertyDTO.TypeEnum;
    /**
     * Значение настройки
     */
    value?: string;
};
export namespace KeyPropertyDTO {
    export type TypeEnum = 'CAMERA' | 'DASHBOARD';
    export const TypeEnum = {
      CAMERA: 'CAMERA' as TypeEnum,
      DASHBOARD: 'DASHBOARD' as TypeEnum
    };
}