/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ViolationInfoDTO } from './violationInfoDTO';

/**
 * Данные о объекте карты
 */
export type LayerSingleObjectDTO = { 
    /**
     * Адрес объекта
     */
    address?: string;
    /**
     * Количество проверок
     */
    checksCount?: number;
    /**
     * Идентификатор Района
     */
    districtId?: string;
    /**
     * Идентификтаор объекта на карте
     */
    featureId?: string;
    /**
     * Баласосодержатель
     */
    holder?: string;
    /**
     * Идентификатор объекта в слое
     */
    objectId?: string;
    /**
     * Идентификатор округа
     */
    regionId?: string;
    /**
     * Количество нарушений группы CITIZEN
     */
    violationCitizen?: number;
    /**
     * Количество нарушений группы GOVERNMENT
     */
    violationGovernment?: number;
    /**
     * Нарушения
     */
    violations?: ViolationInfoDTO[];
    /**
     * Количество нарушений
     */
    violationsCount?: number;
};