/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Сущность слоя.
 */
export type LayerDTO = { 
    /**
     * Алиас слоя
     */
    alias?: string;
    /**
     * Тип слоя
     */
    businessType?: LayerDTO.BusinessTypeEnum;
    /**
     * Дата создания
     */
    creationDate?: Date;
    /**
     * Описание слоя
     */
    description?: string;
    /**
     * Активирован ли слой
     */
    enabled?: boolean;
    /**
     * Идентификатор слоя
     */
    id?: number;
    /**
     * Дата модифицирования
     */
    modificationDate?: Date;
    /**
     * Имя слоя
     */
    name?: string;
    /**
     * Ревизия данных
     */
    revisionId?: number;
    /**
     * Порядок сортировки
     */
    sortOrder?: number;
    /**
     * Тип слоя
     */
    srcType?: string;
};
export namespace LayerDTO {
    export type BusinessTypeEnum = 'alias' | 'dimension' | 'UNKNOWN';
    export const BusinessTypeEnum = {
      Alias: 'alias' as BusinessTypeEnum,
      Dimension: 'dimension' as BusinessTypeEnum,
      UNKNOWN: 'UNKNOWN' as BusinessTypeEnum
    };
}