/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Данные алиаса
 */
export type LayerAliasDTO = { 
    /**
     * Алиас
     */
    alias?: string;
    /**
     * Идентификатор алиаса.
     */
    id?: number;
    /**
     * Тип алиаса.
     */
    type?: LayerAliasDTO.TypeEnum;
};
export namespace LayerAliasDTO {
    export type TypeEnum = 'alias' | 'dimension' | 'UNKNOWN';
    export const TypeEnum = {
      Alias: 'alias' as TypeEnum,
      Dimension: 'dimension' as TypeEnum,
      UNKNOWN: 'UNKNOWN' as TypeEnum
    };
}