/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Данные о объектах с нарушениями
 */
export type LayerObjectDTO = { 
    /**
     * Количество объектов c нарушениями
     */
    amount?: number;
    /**
     * Количество объектов в данном разрезе
     */
    amountObject?: number;
    /**
     * Количество проверенных объектов
     */
    checkAmount?: number;
    /**
     * Код цвета
     */
    colorCode?: string;
    /**
     * идентификатор района
     */
    districtId?: string;
    /**
     * идентификатор объекта
     */
    featureId?: string;
    /**
     * Наличие фото/видео
     */
    hasfotovideo?: boolean;
    /**
     * Широта
     */
    latitude?: string;
    /**
     * Долгота
     */
    longitude?: string;
    /**
     * идентификатор округа
     */
    regionId?: string;
};