/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Легенда для карты, редактируемая
 */
export type LegendEditingDTO = { 
    /**
     * Отображаемый цвет
     */
    color?: string;
    /**
     * Значение цвета
     */
    colorValue?: string;
    /**
     * Легенда
     */
    description?: string;
    /**
     * Смайлик
     */
    emoji?: string;
    /**
     * Идентификатор легенды
     */
    id?: number;
    /**
     * Уровень отображения
     */
    level?: LegendEditingDTO.LevelEnum;
    /**
     * Описание уровня
     */
    levelDescription?: string;
    /**
     * Максимальный процент по записи
     */
    maxPercent?: number;
    /**
     * Минимальный процент по записи
     */
    minPercent?: number;
    /**
     * Флаг использования цветов в Диаграммах отчёта
     */
    report?: boolean;
    /**
     * Сезон
     */
    season?: LegendEditingDTO.SeasonEnum;
    /**
     * Описание сезона
     */
    seasonDescription?: string;
    /**
     * Порядок сортировки
     */
    sortOrder?: number;
    /**
     * Тема
     */
    theme?: string;
};
export namespace LegendEditingDTO {
    export type LevelEnum = 'moscow.russia' | 'regions.moscow.russia' | 'districts.regions.moscow.russia' | 'report' | 'dashboard' | 'dashboard.dashlet' | 'ts' | 'UNKNOWN';
    export const LevelEnum = {
      MoscowRussia: 'moscow.russia' as LevelEnum,
      RegionsMoscowRussia: 'regions.moscow.russia' as LevelEnum,
      DistrictsRegionsMoscowRussia: 'districts.regions.moscow.russia' as LevelEnum,
      Report: 'report' as LevelEnum,
      Dashboard: 'dashboard' as LevelEnum,
      DashboardDashlet: 'dashboard.dashlet' as LevelEnum,
      Ts: 'ts' as LevelEnum,
      UNKNOWN: 'UNKNOWN' as LevelEnum
    };
    export type SeasonEnum = 'all' | 'winter' | 'SYS' | 'svod';
    export const SeasonEnum = {
      All: 'all' as SeasonEnum,
      Winter: 'winter' as SeasonEnum,
      SYS: 'SYS' as SeasonEnum,
      Svod: 'svod' as SeasonEnum
    };
}