/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Легенда для карты
 */
export type LegendDTO = { 
    /**
     * Отображаемый цвет
     */
    color?: string;
    /**
     * Значение цвета
     */
    colorValue?: string;
    /**
     * Легенда
     */
    description?: string;
    /**
     * Смайлик
     */
    emoji?: string;
    /**
     * Максимальный процент по записи
     */
    maxPercent?: number;
    /**
     * Минимальный процент по записи
     */
    minPercent?: number;
    /**
     * Тема
     */
    theme?: string;
};