/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ViolationForTableDTO } from './violationForTableDTO';

/**
 * Данные о нарушении для таблицы
 */
export type ObjectForTableDTO = { 
    /**
     * Адрес
     */
    address?: string;
    /**
     * Типы (описания) нарушений
     */
    defectTypes?: string;
    /**
     * ID района
     */
    districtId?: string;
    /**
     * Наименование района
     */
    districtName?: string;
    /**
     * Номер объекта (featureId)
     */
    featureId?: string;
    /**
     * Есть ли среди нарушений нарушение с фото/видео
     */
    hasFotoVideo?: boolean;
    /**
     * Есть ли среди нарушений критичное
     */
    isCritical?: boolean;
    /**
     * Есть ли среди нарушений систематические
     */
    isSystematic?: boolean;
    /**
     * Идентификатор объекта
     */
    objectId?: string;
    /**
     * Тип объекта
     */
    objectType?: string;
    /**
     * Сокращённое наименование типа объекта на английском
     */
    objectTypeCode?: string;
    /**
     * Наименование округа
     */
    okrugName?: string;
    /**
     * Держатель объекта
     */
    ownerName?: string;
    /**
     * ID округа
     */
    regionId?: string;
    /**
     * Источник контроля
     */
    source?: string;
    /**
     * Нарушения
     */
    violations?: ViolationForTableDTO[];
    /**
     * Количество нарушений
     */
    violationsCount?: number;
};