/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LegendEditingDTO } from './legendEditingDTO';

export type PageResultLegendEditingDTO = { 
    /**
     * Обекты страницы
     */
    objects?: LegendEditingDTO[];
    /**
     * Номер страницы
     */
    pageNumber?: number;
    /**
     * Количество элементов на странице
     */
    pageSize?: number;
    /**
     * Общее количество элементов
     */
    totalElements?: number;
    /**
     * Общее количество страниц
     */
    totalPages?: number;
};