/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Загружаемый файл отчёта 
 */
export type ReportDTO = { 
    /**
     * Ссылка на файл
     */
    data?: string;
    /**
     * Дата отчёта
     */
    date?: string;
    /**
     * Имя файла
     */
    name?: string;
    /**
     * Тип отчёта
     */
    type?: string;
};