/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JsonNode } from './jsonNode';

/**
 * Информация о отчёте
 */
export type ReportInfoDTO = { 
    /**
     * Цветовая схема
     */
    colorSchema?: any;
    /**
     * Идентификатор отчёта
     */
    id?: number;
    /**
     * Сезон
     */
    season?: string;
    semantic?: JsonNode;
    /**
     * Тип
     */
    type?: string;
};