/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Фото с нарушения
 */
export type ViolationFotoDTO = { 
    /**
     * Тип
     */
    mimeType?: string;
    /**
     * Название
     */
    name?: string;
    /**
     * Размер
     */
    size?: number;
    /**
     * Ссылка на фото
     */
    url?: string;
};