/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WidgetElement } from './widgetElement';

export type WidgetFilter = { 
    /**
     * Данные для виджета <Типы нарушений>
     */
    defects?: WidgetElement[];
    /**
     * Данные для виджета <Районы>
     */
    districts?: WidgetElement[];
    /**
     * Данные для виджета <События>
     */
    events?: WidgetElement[];
    /**
     * Данные для виджета <Объекты>
     */
    objects?: WidgetElement[];
    /**
     * Данные для виджета <Округа>
     */
    regions?: WidgetElement[];
    /**
     * Данные для виджета <Группы источников>
     */
    sourceGroups?: WidgetElement[];
    /**
     * Данные для виджета <Источники>
     */
    sources?: WidgetElement[];
};