const TEN_PERCENT = 10;
const TWENTY_PERCENT = 20;
const THIRTY_PERCENT = 30;
const FORTY_PERCENT = 40;
const FIFTY_PERCENT = 50;
const SIXTY_PERCENT = 60;
const SEVENTY_PERCENT = 70;
const EIGHTY_PERCENT = 80;
const NINTY_PERCENT = 90;
const ONE_HUNDRED_PERCENT = 100;

const PERCENT = {
  TEN_PERCENT,
  TWENTY_PERCENT,
  THIRTY_PERCENT,
  FORTY_PERCENT,
  FIFTY_PERCENT,
  SIXTY_PERCENT,
  SEVENTY_PERCENT,
  EIGHTY_PERCENT,
  NINTY_PERCENT,
  ONE_HUNDRED_PERCENT,
};

export default PERCENT;
